name: Sync Wallpaper to S3
on:
  schedule:
    - cron: '2 7,16 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      - name: Install dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Build
        run: go build -o bing
      - name: Upload to S3
        run:
          ./bing upload --type s3 --index 0 --market zh-CN --resolution 1920
        env:
          bucket: ${{ secrets.BUCKET }}
          endpoint: ${{ secrets.ENDPOINT }}
          access_key: ${{ secrets.ACCESS_KEY }}
          access_key_secret: ${{ secrets.ACCESS_KEY_SECRET }}
          region: ${{ secrets.REGION }}